### PR TITLE
8 new actions Implemented

### PR DESCRIPTION
**Pull request by kaumudpa**
Did some corrections in utils_js.dart to make sure `readContract`, `readContracts ` & `getChains` work. (No idea why this was broken)

Also  implemented 

 `getChains`
 `disconnect`
`switchAccount`
`switchChain`
`verifyMessage`
`waitForTransactionReceipt`
`watchAccount`
`watchConnections`

@Chralu Requesting you to kindly review these and merge this if everything looks ok.

### CODE REVIEW

**Comment by redDwarf03** [comment]
Hello. we have just merged PR https://github.com/archethic-foundation/wagmi_flutter_web/pull/42 in same time of your PR... Could you rebase this PR please

**Comment by kaumudpa** [comment]
Rebased . Please check - @redDwarf03  & @Chralu

**Comment by redDwarf03** [comment]
I don't understand why in "files changed" https://github.com/archethic-foundation/wagmi_flutter_web/pull/51/files#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15. I have the PR changes on the wagmiContext?

**Comment by kaumudpa** [comment]
Hi @redDwarf03, I am sorry but i am unable to understand. Can you please point Me to What happened?

**Comment by redDwarf03** [comment]
I don't understand why your PR isn't just the difference between the main branch and your work. In your PR there are the additions of the PR on wagmiContext.

**Comment by kaumudpa** [comment]
@redDwarf03 Kindly hold off this PR for few hours, Let me reset my branch, add the respective files again and reopen a new PR. Also please avoid new commits to the main branch till then.

**Comment by kaumudpa** [comment]
resolved via #54

**Pull request closed without merging**
