### PR TITLE
feat: ✨ getTransactionReceipt

### PR DESCRIPTION
**Pull request by kaumudpa**
`getTransactionReceipt` Implemented

### CODE REVIEW

**Comment by kaumudpa** [comment]
Hi @redDwarf03 Requesting you to check & merge this. Also we need a better layout for Example app - its becoming messier as we keep adding new feats - Any suggestions?

**Comment by redDwarf03** [comment]
Hi. Ok i will check it and merge
Agree about example app..... 

NB: i open a discussions feed on the repo with issue to discuss
NB: Sorry, i insist but i want to let my analysis_options.yaml

**Comment by kaumudpa** [comment]
Also requesting you to first check and merge PR's every-time BEFORE you directly commit and push to this repo.

Unnecessary conflicts happen to resolve in the downstreams.

**Comment by redDwarf03** [comment]
My bad... Sorry.
I will use PR now instead of commit directly
I tried to rebase your PR but i can't push -f on your PR...

**Comment by redDwarf03** [comment]
I will copy your PR content in main branch and after that, i will improve process.. sorry again

**Comment by kaumudpa** [comment]
You want us to resolve conflicts here?

**Comment by redDwarf03** [comment]
no no. i will take your code, push in main branch directly. i won't merge this PR.
And after that, we will work only with PR. Let me few minutes please

**Comment by redDwarf03** [comment]
included in main branch via https://github.com/archethic-foundation/wagmi_flutter_web/commit/73e9cf02e59949a3e9064ac5264d39c84583201a commit

I close this PR

**Pull request closed without merging**
