### PR TITLE
Only Transport config

### PR DESCRIPTION
**Pull request by kaumudpa**
This is a draft PR to explore #41 

Introduces a new transportOnlyConfig - Once initialised - We can call any action with only this config with an additional parameter.

@Chralu Requesting you to kindly give your inputs.

### CODE REVIEW

**Comment by Chralu** [comment]
Hi @kaumudpa ,

Sry for the long delay . I haven't had time to review your PR yet.

I look at it monday.

**Comment by kaumudpa** [comment]
Please do - We have also successfully implemented `dissconnect` (This was really complex as),  `watchPendingTransactions `, `watchConnections `, `verifyMessage `, `switchChain `, `switchAccount` & `getConnectors ` . 

Will open a PR for those actions once we decide on this issue.

**Comment by kaumudpa** [comment]
Hi @Chralu can you please look into this today and give your comments. We have multiple other action implemented waiting for the PR Creation.

**Comment by kaumudpa** [comment]
> Hi @kaumudpa,
> 
> IMO, if we introduce a multi-setup system, it should allow to change all the config parameters ( not the transport only).
> 
> Following that idea, I still have a preference for a solution like [this one](https://github.com/archethic-foundation/wagmi_flutter_web/pull/42).
> 
> I finish the implementation of #42 to give a final idea of the thing.

@Chralu  Your solution is elegant. Lets get it merged.

**Pull request closed without merging**
