### PR TITLE
Chralu/issue41

### LINKED ISSUE #41: Multi Config & Ability to use Different config for different actions.
### Is your feature request related to a problem?

_No response_

### Describe the solution you'd like

@Chralu Just saw your implementation in the latest merge. You have added a transport builder which can take in WSS and/or HTTP urls. Now Once we provide these all the traffic to the blockchain are passed via these transportbuilder only. but lets say we have a situation where lets say we want to .

1. Use default connected wallet for sending  `call` or `sendTransaction` action to the blockchain.
&
2. Use WSS transport url for watchContractEvent.

How do you propose we address this situation?

### Additional context

_No response_

### Epic

_No response_

### PR DESCRIPTION
**Pull request by Chralu**
fixes #41

This solution is a proposal.
It reflects the Web3modal config API :
 - creation of a `Config` is done through `Web3Modal.defaultWagmiConfig`
 - `Config` is retained on the `Dart` side.
 - `Config` must be passed as parameter to each action.

For now, the only action to use that mecanism is `getAccount`.

@kaumudpa any thoughts ?

### CODE REVIEW

**Comment by kaumudpa** [comment]
This could be one approach. 

What i had in mind was something like.

1.lets keep 1 default config as we currently have. This default config will be used by default by all the action unless we specify other config with an action.

2. Also Keep this ability of yours to spawn config as necessary.

3. Introduce a Transport only config.

Acrions will use default config if any other config is not provided.

**Comment by kaumudpa** [comment]
@Chralu help me understand your solution here please. - I am kind of confused with your implementation.

**Comment by Chralu** [comment]
There are two new objects : 
 - `JSWagmiConfig` : a wagmi config
 - `JSAppKit` : a web3modal instance
 
 Those objects are created by Web3Modal/Wagmi JS functions.
 
 The dart code retrieves and uses the `JS***` objects : There is no conversion to Dart types, but I added two alias types `WagmiConfig` and `AppKit`.
 
 I did not convert JS objects to Dart ones to avoid losing data, and that way it seems we are keeping a reference to the JS object.
 I'm not sure about the internal behavior of JS references, but this seems to "work" ...

**Comment by kaumudpa** [comment]
Hi @Chralu

Can you please look into this https://github.com/0xMetaLab/wagmi_flutter_web/tree/TransportConfig and let me know your views?

**Comment by kaumudpa** [comment]
> https://github.com/0xMetaLab/wagmi_flutter_web/tree/TransportConfig

@Chralu  Please check #44

**Comment by Chralu** [comment]
@kaumudpa I have finished that implementation.

In the example app, there are two wagmi configurations objects declared.
You can use the one you want in each wagmi call.

The `Test switch config` tab demonstrates this.

**Comment by kaumudpa** [comment]
Hi @Chralu This looks good to me. Lets get this merged.

**Review by redDwarf03 — APPROVED** [review]

**Pull request merged**
