### PR TITLE
refactor: :recycle: Migrate Javascript code to Typescript.

### PR DESCRIPTION
**Pull request by Chralu**
As the lib grows, type checking becomes absolutely necessary.

This will prevent many programming issues.

@redDwarf03 @kaumudpa we need to synchronize PRs approvals because this one moves JS files.

### CODE REVIEW

**Comment by kaumudpa** [comment]
Got It. We need to hold this one till we merge other current PR's.

**Comment by Chralu** [comment]
That's a way to do it. 
In that case, we must not open new PRs until the pipe is empty.

**Comment by kaumudpa** [comment]
Ok. No new PR's will be opened from our end till this one is merged.

**Comment by kaumudpa** [comment]
Wanted to ask - shall we hold this till we commit all the possible implementations?

**Comment by redDwarf03** [comment]
> Wanted to ask - shall we hold this till we commit all the possible implementations?

No, ideally i would like to merge this PR just after your PR with new methods

**Comment by kaumudpa** [comment]
What is the eta OF this and other PR'S to be merged? Cause we wont be able to work until the main branch is merged with these PR'S as we need to sync our fork accordingly.

**Comment by redDwarf03** [comment]
I started the merge but now I have to go to the cinema 😅😅 so I merge in a few hours

**Comment by redDwarf03** [comment]
PR updated with last PR

**Pull request merged**
